### ISSUE TITLE
What's this for?

### ISSUE THREAD

**Issue by pol-todo** [ualsg/InstantCITY#1]
Hi all, 

More of a semantic issue, what's this project trying to accomplish? Maybe a small blurb in the README.md would be helpful. Sounds like a neat project. 

Best,

Paul

**Comment by Iceofsky** [comment]
Hi, the paper behind this repo has been published and we are updating the Repo with more information. Please check back soon!

**Comment by fbiljecki** [comment]
Hi @paulterinho, thanks for your interest in this repo! The paper about this project was published last week: https://doi.org/10.1016/j.isprsjprs.2022.11.005
The readme is being improved.

**Comment by pol-todo** [comment]
Congratulations! Thanks Filip, I'll check it out. Thanks so much for the
notification!
